//import generateSidebar from "../utils/auto-gen-sidebar.mjs";

export default {
//    "/general/": generateSidebar("general"),
//    "/nipple/": generateSidebar("nipple"),
//    "/prostate/": generateSidebar("prostate"),
//    "/penis/": generateSidebar("penis"),
//    "/hypnosis/": generateSidebar("hypnosis"),
//    "/squirting/": generateSidebar("squirting"),
//  { text: '简介', link: '/general/' },
//  { text: '', link: '' },
//  { text: '绪论',
//      items: [
//      { text: '', link: '' },
//      ],
//  },

    '/general/': [
        { text: '简介', link: '/general/' },
        { text: '雌性高潮开发的原理', link: '/general/theory' },
        { text: '雌性高潮的阶段', link: '/general/levels' },
        { text: '全身性感带开发', link: '/general/development' },
        { text: '全身性感带开发', link: '/general/prolongation' },
        { text: '全身性感带开发', link: '/general/play' },
    ],
    '/nipple/':[
        { text: '简介', link: '/nipple/' },
        { text: '乳首开发的原理', link: '/nipple/principle' },
        { text: '乳首开发的常见误区', link: '/nipple/principle-myths' },
        { text: '开发', link: '/nipple/development' },
        { text: '风险', link: '/nipple/development-risk' },
        { text: '手工开发', link: '/nipple/development-hand' },
        { text: '磁针贴开发', link: '/nipple/development-acupuncture' },
        { text: '超量恢复开发', link: '/nipple/development-compensation' },
        { text: '加速开发的几点意见', link: '/nipple/development-acceleration' },
        { text: '开发等级', link: '/nipple/development-level' },
        { text: '自慰', link: '/nipple/masturbation' },
        { text: '准备', link: '/nipple/masturbation-preparation' },
        { text: '技法', link: '/nipple/masturbation-technique' },
        { text: '快感', link: '/nipple/masturbation-pleasure' },
        { text: '高潮', link: '/nipple/masturbation-orgasm' },
        { text: '玩具', link: '/nipple/masturbation-toy' },
        { text: '附录', link: '/nipple/appendix' },
        { text: '常见问题回答', link: '/nipple/appendix-faq' },
    ],
    '/prostate/':[
        { text: '简介', link: '/prostate/' },
        { text: '后庭开发', link: '/prostate/anal' },
        { text: '原理', link: '/prostate/anal-principle' },
        { text: '基本步骤', link: '/prostate/anal-step' },
        { text: '安全问题', link: '/prostate/anal-safety' },
        { text: '准备工作', link: '/prostate/anal-preparation' },
        { text: '热身', link: '/prostate/anal-warmup' },
        { text: '玩具', link: '/prostate/anal-toys' },
        { text: '进阶玩法', link: '/prostate/anal-advanced' },
        { text: 'Aneros概述', link: '/prostate/introduction' },
        { text: '流程', link: '/prostate/introduction-procedure' },
        { text: '原理', link: '/prostate/introduction-principle' },
        { text: '高潮', link: '/prostate/introduction-orgasm' },
        { text: '高级技能', link: '/prostate/introduction-advanced' },
        { text: '附录', link: '/prostate/appendix' },
        { text: '常见误解', link: '/prostate/appendix-misconceptions' },
        { text: '常见问题', link: '/prostate/appendix-faq' },
        { text: '术语表', link: '/prostate/appendix-glossary' },
        { text: '与女性的关系', link: '/prostate/appendix-women' },
        { text: '健康', link: '/prostate/appendix-health' },
        { text: '历史', link: '/prostate/appendix-history' },
    ],
    '/penis/':[
        { text: '简介', link: '/penis/' },
        { text: '阴茎雌性高潮的开发', link: '/penis/basic' },
        { text: '前列腺增强的阴茎雌性高潮', link: '/penis/prostate' },
        { text: '睾丸雌性高潮的开发', link: '/penis/testicle' },
        { text: '利用飞机杯达到雌性高潮', link: '/penis/masturbator' },
        { text: '在做爱中达到雌性高潮', link: '/penis/vagina' },
    ],
    '/hypnosis/':[
        { text: '简介', link: '/hypnosis/' },
        { text: '基础知识', link: '/hypnosis/introduction' },
        { text: '催眠自慰的原理', link: '/hypnosis/theory' },
        { text: '催眠音声的使用', link: '/hypnosis/audio' },
        { text: '常见问题', link: '/hypnosis/audio-faq' },
        { text: '进入和保持催眠状态', link: '/hypnosis/audio-mental-state' },
        { text: '四个阶段的目标和做法', link: '/hypnosis/audio-map' },
        { text: '小技巧', link: '/hypnosis/audio-tricks' },
        { text: '音声等资源获取', link: '/hypnosis/resource' },
    ],
    '/squirting/':[
        { text: '简介', link: '/squirting/' },
        { text: '概述', link: '/squirting/definition' },
        { text: '可能性', link: '/squirting/definition-possibility' },
        { text: '准备工作', link: '/squirting/preparation' },
        { text: '联系', link: '/squirting/connnection' },
        { text: '自慰与高潮', link: '/squirting/masturbateANDorgasm' },
        { text: '阴蒂潮吹', link: '/squirting/masturbateANDorgasm-clitoris' },
        { text: '乳首潮吹', link: '/squirting/masturbateANDorgasm-nipple' },
        { text: '玩具', link: '/squirting/toys' },
        { text: '后记', link: '/squirting/conclusion' },
    ],

    '/h-life/nipple/':[
        { text: '绪论',
            items: [
            { text: '关于乳首（乳首与性感的说明）', link: '/h-life/nipple/intro/page-90.html', target: '_self', },
            { text: '关于乳首开发', link: './nipple/intro/page-9.html' },
            { text: '什么是乳首自慰', link: './nipple/intro/page-146.html' },
            { text: '【新手向】乳首开发入门讲座', link: './nipple/intro/page-41.html' },
            ],
        },
        { text: '乳首开发与乳首高潮的说明',
            items: [
                { text: '关于乳首开发的风险', link: './nipple/kaihatsu+iki/page-10.html' },
                { text: '关于乳首的敏感度等级', link: './nipple/kaihatsu+iki/page-1.html' },
            ],
        },

    ],
}
//{ text: '', link: '' },